### ISSUE TITLE
Where can one obtain the 'doom-1.3' dependency?

### ISSUE THREAD

**Issue by flexibeast** [8cylinder/showcss-mode#8]
It doesn't seem to be available on the GELPA, MELPA or Marmalade repos ....

**Comment by tarsius** [comment]
From here: https://github.com/emacsorphanage/doom.
It should bee on Melpa soon: https://github.com/milkypostman/melpa/pull/3514.
More info: https://github.com/toroidal-code/dom.el/issues/2.

**Comment by purcell** [comment]
It's on MELPA and MELPA Stable now, so this can be closed.

**Comment by 8cylinder** [comment]
Thanks everyone for your efforts.
